center_fsp/center_fsp/urls.py
from django.conf import settings
import django.conf.urls.static
import django.contrib
import django.contrib.auth.urls
from django.urls import include, path

urlpatterns = [
    path("", include("homepage.urls")),
    path("calendar/", include("meropriations_calendar.urls")),
    path("meropriations/", include("meropriations.urls")),
    path("stats/", include("stats.urls")),
    path("feedback/", include("feedback.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("allauth.urls")),
    path("admin/", django.contrib.admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += django.conf.urls.static.static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT,
)

urlpatterns += django.conf.urls.static.static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

center_fsp/homepage/urls.py
from django.urls import path

import homepage.views

app_name = "homepage"
urlpatterns = [
    path("", homepage.views.Home.as_view(), name="main"),
]

center_fsp/stats/urls.py
from django.urls import path

from stats.views import (
    RegionStatisticsView,
    TeamStatisticsView,
    UserStatisticsView,
)

app_name = "stats"
urlpatterns = [
    path("regions/", RegionStatisticsView.as_view(), name="region_statistics"),
    path("users/", UserStatisticsView.as_view(), name="user_statistics"),
    path("teams/", TeamStatisticsView.as_view(), name="team_statistics"),
]

center_fsp/users/urls.py
from allauth.account.views import ConfirmEmailView
from allauth.account.views import EmailVerificationSentView
from allauth.account.views import EmailView
from allauth.account.views import LoginView
from allauth.account.views import LogoutView
from allauth.account.views import PasswordChangeView
from allauth.account.views import PasswordResetDoneView
from allauth.account.views import PasswordResetFromKeyDoneView
from allauth.account.views import PasswordResetFromKeyView
from allauth.account.views import PasswordResetView
from django.urls import path, re_path, reverse_lazy

from users import forms
from users import views

app_name = "users"

urlpatterns = [
    path(
        "account/",
        views.AccountView.as_view(),
        name="profile",
    ),
    path(
        "signup/",
        views.RegionalRepresentativeSignupView.as_view(),
        name="signup",
    ),
    path(
        "login/",
        LoginView.as_view(
            form_class=forms.LoginForm,
            template_name="users/login.html",
        ),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path(
        "confirm-email/",
        EmailVerificationSentView.as_view(
            template_name="users/confirm_email.html",
        ),
        name="confirm_email",
    ),
    re_path(
        r"^confirm-email/(?P<key>[-:\w]+)/$",
        ConfirmEmailView.as_view(
            template_name="users/confirm_email_from_sent.html",
        ),
        name="account_confirm_email",
    ),
    path(
        "email/",
        EmailView.as_view(
            form_class=forms.EmailForm,
            template_name="users/email_change.html",
        ),
        name="email_change",
    ),
    path(
        "password/change/",
        PasswordChangeView.as_view(
            form_class=forms.ChangePasswordForm,
            template_name="users/password_change.html",
            success_url=reverse_lazy("users:password_change_done"),
        ),
        name="password_change",
    ),
    path(
        "password/change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password/reset/",
        PasswordResetView.as_view(
            form_class=forms.ResetPasswordForm,
            template_name="users/password_reset.html",
        ),
        name="password_reset",
    ),
    path(
        "password/reset/done/",
        PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    re_path(
        r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        PasswordResetFromKeyView.as_view(
            form_class=forms.ResetPasswordKeyForm,
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "password/reset/key/done/",
        PasswordResetFromKeyDoneView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path(
        "users/",
        views.UsersView.as_view(),
        name="users",
    ),
    path(
        "users/<int:pk>/",
        views.UserDetailView.as_view(),
        name="user_detail",
    ),
    path(
        "<int:pk>/update-region/",
        views.update_user_region,
        name="update_user_region",
    ),
    path(
        "<int:pk>/remove-region/",
        views.remove_user_region,
        name="remove_user_region",
    ),
]

center_fsp/users/models.py
__all__ = ()
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from sorl.thumbnail import delete, get_thumbnail


class Region(models.Model):
    name = models.CharField(
        verbose_name="регион",
        max_length=150,
        null=True,
    )

    class Meta:
        ordering = ("name",)
        verbose_name = "регион"
        verbose_name_plural = "регионы"

    def __str__(self):
        return self.name


class User(AbstractUser):
    avatar = models.ImageField(
        _("avatar"),
        upload_to="avatars/",
        null=True,
        blank=True,
    )
    region = models.ForeignKey(
        Region,
        verbose_name="регион",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )

    def has_avatar(self):
        return self.avatar and self.avatar.url is not None

    def get_small_avatar(self):
        return get_thumbnail(self.avatar, "80", crop="center").url

    def get_large_avatar(self):
        return get_thumbnail(self.avatar, "200", crop="center").url

    def save(self, *args, **kwargs):
        try:
            old = User.objects.get(pk=self.pk)
            if old.has_avatar() and not self.has_avatar():
                delete(old.avatar)
        except User.DoesNotExist:
            pass

        super().save(*args, **kwargs)

    class Meta:
        ordering = ("region",)
        verbose_name = "пользователь"
        verbose_name_plural = "пользователи"

    def __str__(self):
        return self.username

center_fsp/users/forms.py
__all__ = ()
from allauth.account.forms import (
    AddEmailForm,
    ChangePasswordForm,
    LoginForm,
    ResetPasswordForm,
    ResetPasswordKeyForm,
    SignupForm,
)
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm
from django.utils.translation import gettext_lazy as _

from users.models import Region, User


class BootstrapFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if len(self.visible_fields()) == 1:
            self.visible_fields()[0].field.widget.attrs[
                "class"
            ] = "form-control input-field-only-one"
        else:
            for field in self.visible_fields():
                field.field.widget.attrs["class"] = "form-control input-field"
                if isinstance(field.field.widget, forms.CheckboxInput):
                    field.field.widget.attrs["class"] = "form-check-input"

        self.update_errors_class()

    def update_errors_class(self):
        for field in self.visible_fields():
            if self.errors.get(field.name):
                if "is-invalid" not in field.field.widget.attrs["class"]:
                    field.field.widget.attrs["class"] += " is-invalid"

    def add_error(self, field, error):
        super().add_error(field, error)
        self.update_errors_class()


class UserForm(BootstrapFormMixin, UserChangeForm):
    password = None

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields[User.email.field.name].widget.attrs["readonly"] = True
        self.fields[User.email.field.name].widget.attrs["disabled"] = True
        self.fields[User.avatar.field.name].widget.attrs["class"] += " d-none"

    class Meta(UserChangeForm.Meta):
        model = get_user_model()

        fields = [
            User.username.field.name,
            User.email.field.name,
            User.avatar.field.name,
        ]


class UserRegionForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["region"]
        widgets = {"region": forms.Select(attrs={"class": "form-control"})}


class RegionalRepresentativeSignupForm(BootstrapFormMixin, SignupForm):
    def __init__(self, *args, **kwargs):
        kwargs.pop("instance", None)
        super().__init__(*args, **kwargs)

    def save(self, request):
        user = super().save(request)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.region = self.cleaned_data["region"]
        user.save()
        return user

    region = forms.ModelChoiceField(
        queryset=Region.objects.all(),
        required=True,
        label=_("Region"),
        widget=forms.Select(attrs={"class": "form-select"}),
    )
    first_name = forms.CharField(
        required=True,
        label=_("First Name"),
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": _("Enter your first name"),
            },
        ),
    )
    last_name = forms.CharField(
        required=True,
        label=_("Last Name"),
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": _("Enter your last name"),
            },
        ),
    )


class EmailForm(BootstrapFormMixin, AddEmailForm):
    pass


class LoginForm(BootstrapFormMixin, LoginForm):
    pass


class ChangePasswordForm(BootstrapFormMixin, ChangePasswordForm):
    pass


class ResetPasswordForm(BootstrapFormMixin, ResetPasswordForm):
    pass


class ResetPasswordKeyForm(BootstrapFormMixin, ResetPasswordKeyForm):
    pass

center_fsp/users/views.py
__all__ = ()
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import translation
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
import django.views.generic
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, FormView

from users.forms import (
    RegionalRepresentativeSignupForm,
    UserForm,
    UserRegionForm,
)
from users.models import User


class AccountView(LoginRequiredMixin, FormView):
    template_name = "users/profile.html"
    form_class = UserForm

    def get_initial(self):
        return {
            "username": self.request.user.username,
            "email": self.request.user.email,
            "avatar": self.request.user.avatar,
        }

    def post(self, request, *args, **kwargs):
        post = request.POST.copy()
        post["email"] = request.user.email
        user_form = UserForm(post, request.FILES, instance=request.user)
        new_username = user_form.cleaned_data.get("username")

        if new_username != request.user.username:
            if user_form.is_valid():
                if User.objects.filter(username=new_username).exists():
                    user_form.add_error(
                        "username",
                        _("username_is_already_taken"),
                    )
        elif user_form.is_valid():
            user_form.save()
            return redirect("users:profile")

        return render(request, "users/profile.html", {"form": user_form})


class PasswordChangeDoneView(views.PasswordChangeDoneView):
    pass


@method_decorator(staff_member_required, name="dispatch")
class RegionalRepresentativeSignupView(CreateView):
    model = User
    form_class = RegionalRepresentativeSignupForm
    template_name = "users/signup.html"

    def get(self, request, *args, **kwargs):
        translation.activate(request.LANGUAGE_CODE)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Добавляем переводы для заголовка и кнопки
        context["title"] = _("Register Regional Representative")
        context["submit_text"] = _("Register")
        return context

    def form_valid(self, form):
        user = form.save(request=self.request)
        user.first_name = form.cleaned_data["first_name"]
        user.last_name = form.cleaned_data["last_name"]
        user.region = form.cleaned_data["region"]
        user.is_staff = False
        user.save()
        return redirect("users:users")


@method_decorator(staff_member_required, name="dispatch")
class UsersView(django.views.generic.ListView):
    template_name = "users/list_users.html"
    context_object_name = "users"
    queryset = User.objects.exclude(is_superuser=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Представители"
        return context


class UserDetailView(DetailView):
    model = User
    template_name = "users/user_detail.html"
    context_object_name = "personal"

    def get_object(self, queryset=None):
        return get_object_or_404(User, pk=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Проверяем, является ли текущий пользователь суперюзером
        if self.request.user.is_superuser:
            context["region_form"] = UserRegionForm(instance=self.object)

        return context


# Обработка изменения региона пользователя
def update_user_region(request, pk):
    user = get_object_or_404(User, pk=pk)

    # Проверяем, является ли текущий пользователь суперюзером
    if not request.user.is_superuser:
        messages.error(request, "У вас нет прав на выполнение этого действия.")
        return redirect("users:user_detail", pk=pk)

    if request.method == "POST":
        form = UserRegionForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, "Регион пользователя успешно обновлен.")
        else:
            messages.error(request, "Ошибка при обновлении региона.")

    return redirect("users:user_detail", pk=pk)


# Обработка удаления региона
def remove_user_region(request, pk):
    user = get_object_or_404(User, pk=pk)

    # Проверяем права суперюзера
    if not request.user.is_superuser:
        messages.error(request, "У вас нет прав на выполнение этого действия.")
        return redirect("users:user_detail", pk=pk)

    user.region = None
    user.save()
    messages.success(request, "Регион был успешно удален.")
    return redirect("users:user_detail", pk=pk)

center_fsp/templates/users/confirm_email.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "email_confirmation" %}{% endblock %}

{% block content %}

<div class="d-flex flex-column mt-5">
  <hr>
  <h1 class="text-center mb-4">{% trans "email_confirmation" %}</h1>
  <p class="text-center">{% trans "email_confirmation_description" %}</p>
  {% if messages %}
    {% for message in messages %}<p class="text-center">({{ message }})</p>{% endfor %}
  {% endif %}
  <hr class="mb-5">
</div>

{% endblock %}

center_fsp/templates/users/confirm_email_from_sent.html
{% extends "base.html" %}
{% load account %}
{% load allauth %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "email_confirmation" %}{% endblock %}

{% block content %}

<div class="d-flex flex-column mt-5">
  <hr>
  <h1 class="text-center mb-4">{% trans "email_confirmation" %}</h1>
  {% if confirmation %}
    {% user_display confirmation.email_address.user as user_display %}
    {% if can_confirm %}
      <p class="text-center">
        {% blocktrans with confirmation.email_address.email as email %}Please confirm that <a href="mailto:{{ email }}">{{ email }}</a> is an email address for user {{ user_display }}.{% endblocktrans %}
      </p>
      {% url "account_confirm_email" confirmation.key as action_url %}
      <div class="d-flex">
        <div class="ms-auto me-auto">
          {% element form method="post" action=action_url %}
            {% slot actions %}
              {% csrf_token %}
              <button class="btn btn-outline">{% trans "Confirm" %}</button>
            {% endslot %}
          {% endelement %}
        </div>
      </div>
    {% else %}
      <p class="text-center">
        {% blocktrans %}Unable to confirm {{ email }} because it is already confirmed by a different account.{% endblocktrans %}
      </p>
    {% endif %}
  {% else %}
    {% url "account_email" as email_url %}
    <p class="text-center">
      {% blocktrans %}This email confirmation link expired or is invalid. Please <a href="{{ email_url }}">issue a new email confirmation request</a>.{% endblocktrans %}
    </p>
  {% endif %}
  <hr class="mb-5">
</div>

{% endblock %}

center_fsp/templates/users/email_change.html
{% extends "base.html" %}
{% load i18n %}
{% load allauth %}

{% block title %}{% trans "email" %}{% endblock %}

{% block content %}

<div class="d-flex flex-column col-10 col-sm-8 col-md-6 col-lg-5 col-xl-4 col-xxl-3 ms-auto me-auto mt-5">
  <h1 class="h3 mb-3 fw-normal text-center">{% trans "email_change" %}</h1>
  {% url 'account_email' as action_url %}
  {% element form method="post" action=action_url %}
    {% slot body %}
      {% csrf_token %}
      <div class="form-group d-flex flex-column">
        <div class="form-floating">
          {% if new_emailaddress %}
            <input type="email" name="email" placeholder="E-mail адрес" autocomplete="email" value="{{ new_emailaddress.email }}" maxlength="320" class="form-control input-field-only-one" readonly="" required="" id="id_email">
            <label for="id_email">{% trans "Email" %}</label>
          {% else %}
            <input type="email" name="email" placeholder="E-mail адрес" autocomplete="email" maxlength="320" class="form-control input-field-only-one" required="" id="id_email">
            <label for="id_email">{% trans "Email" %}</label>
          {% endif %}
          <p class="alert alert-warning center" style="margin-top: 20px;">Отправка подтверждения только на Gmail почту</p>
        </div>

      </div>
    {% endslot %}
    {% slot actions %}
      <div class="d-flex flex-column">
        {% if new_emailaddress %}
          <button class="btn btn-outline ms-auto me-auto mt-3 py-2" type="submit" name="action_send">{% trans "Re-send Verification" %}</button>
          <button class="btn btn-outline-danger ms-auto me-auto mt-3 py-2" type="submit" name="action_remove">{% trans "Cancel" %}</button>
        {% else %}
          <button class="btn btn-outline ms-auto me-auto mt-3 py-2" type="submit" name="action_add">{% trans 'change_email' %}</button>
        {% endif %}
      </div>
    {% endslot %}
  {% endelement %}
</div>

{% endblock %}

center_fsp/templates/users/list_users.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

<div class="container mt-4">
  <h2 class="mb-4">{% trans "Все представители по регионам" %}</h2>

  <div class="card-group row">
    {% for personal in users %}
      {% ifchanged personal.region.name %}
        <h2>{{ personal.region.name }}</h2>
      {% endifchanged %}
      <div class="col-md-4 mb-4">
        <div class="card shadow-sm">
          <img src="{% if personal.has_avatar %}{{ personal.get_small_avatar }}{% else %}{% static 'img/default_user_avatar.jpg' %}{% endif %}" class="card-img-top" alt="{{ personal.username }}'s Avatar">
          <div class="card-body">
            <h5 class="card-title">{{ personal.first_name }} {{ personal.last_name }}</h5>
            <p class="card-text"><strong>{% trans "Username:" %}</strong> {{ personal.username }}</p>
            <p class="card-text"><strong>Регион:</strong> {{ personal.region.name }}</p>
            <a href="{% url 'users:user_detail' personal.pk %}" class="btn btn-primary">
              <i class="bi bi-info-circle"></i> {% trans "Подробнее" %}
            </a>
          </div>
        </div>
      </div>
    {% empty %}
      <p>{% trans "Список пуст" %}</p>
    {% endfor %}
  </div>

  <div class="mt-4">
    <a href="{% url 'users:signup' %}" class="btn btn-success">
      <i class="bi bi-person-plus"></i> {% trans "Новый представитель" %}
    </a>
  </div>
</div>

{% endblock %}

center_fsp/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "authorization" %}{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/users/user-auth.css' %}">
{% endblock %}

{% block content %}

<div class="container">
  <h2>{% trans 'log_in_to' as log_in_to %}</h2>
  <p class="text-center">{% trans 'sign_in' as sign_in %}</p>
  {% include "includes/user_form.html" with title=log_in_to submit_text=sign_in %}
</div>

{% endblock %}

center_fsp/templates/users/password_change.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "password_change" %}{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/userS/user-auth.css' %}">
{% endblock %}

{% block content %}

{% trans "password_change" as password_change %}
{% trans "change_password" as change_password %}
{% include "includes/user_form.html" with title=password_change submit_text=change_password %}

{% endblock %}

center_fsp/templates/users/password_change_done.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "password_changed" %}{% endblock %}

{% block content %}

<div class="d-flex flex-column mt-5">
  <hr>
  <h1 class="text-center mb-4">{% trans "your_password_be_success_changed" %}</h1>
  <a href="{% url 'homepage:main' %}" class="btn btn-outline mx-auto mt-4">{% trans "to_main" %}</a>
  <hr class="mb-5">
</div>

{% endblock %}

center_fsp/templates/users/password_reset.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "password_recovery" %}{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/users/user-auth.css' %}">
{% endblock %}

{% block content %}

{% trans "password_recovery" as password_recovery %}
{% trans "recover" as recover %}
{% include "includes/user_form.html" with title=password_recovery submit_text=recover %}

{% endblock %}

center_fsp/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "password_recovered" %}{% endblock %}

{% block content %}

<div class="d-flex flex-column mt-5">
  <hr>
  <h1 class="text-center mb-4">{% trans "password_reset_completed_success" %}</h1>
  <a href="{% url 'homepage:main' %}" class="btn btn-outline mx-auto mt-4">{% trans "to_main" %}</a>
  <hr class="mb-5">
</div>

{% endblock %}

center_fsp/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "password_recovery" %}{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/users/user-auth.css' %}">
{% endblock %}

{% block content %}

{% trans "password_recovery" as password_recovery %}
{% trans "reset" as reset %}
{% include "includes/user_form.html" with title=password_recovery submit_text=reset %}

{% endblock %}

center_fsp/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "password_recovery" %}{% endblock %}

{% block content %}

<div class="d-flex flex-column mt-5">
  <hr>
  <h1 class="text-center mb-4">{% trans "email_instructions_for_password_recove_sent" %}</h1>
  <a href="{% url 'homepage:main' %}" class="btn btn-outline mx-auto mt-4">{% trans "to_main" %}</a>
  <hr class="mb-5">
</div>

{% endblock %}

center_fsp/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "my_profile" %}{% endblock %}

{% block content %}

<div class="container mt-5">
  <h1 class="text-center mb-4">{% trans "my_profile" %}</h1>
  <form
    class="profile-form d-flex flex-column mx-auto"
    method="post"
    enctype="multipart/form-data"
    style="max-width: 600px;"
  >
    {% csrf_token %}
    <div class="d-flex flex-column flex-md-row align-items-center">
      <!-- Avatar Section -->
      <div class="avatar-container text-center mb-3 mb-md-0">
        <img
          id="avatar"
          src="{% if request.user.has_avatar %}{{ request.user.get_large_avatar }}{% else %}{% static 'img/default_user_avatar.jpg' %}{% endif %}"
          alt="{{ request.user.username }}"
          class="rounded-circle border shadow"
          width="150"
          height="150"
        >
        {% if request.user.has_avatar %}
          <a
            id="delete_avatar"
            class="btn btn-outline-danger btn-sm mt-2"
          >
            {% trans "delete_avatar" %}
          </a>
        {% endif %}
      </div>

      <!-- Form Fields -->
      <div class="form-fields w-100 ms-md-4">
        {% for field in form %}
          <div class="mb-3 {% if forloop.last %}d-none{% endif %}">
            {% if "d-none" not in field.field.widget.attrs.class or "clearablefile" not in field.widget_type %}
              <label for="{{ field.id_for_label }}" class="form-label">
                {{ field.label }}
              </label>
            {% endif %}
            {{ field }}
            {% if field.errors %}
              <div class="text-danger small mt-1">
                {{ field.errors|first }}
              </div>
            {% endif %}
          </div>
        {% endfor %}
      </div>
    </div>

    <!-- Save Button -->
    <button
      id="submit_button"
      type="submit"
      class="btn btn-primary w-100 mt-3 d-none"
    >
      {% trans "save" %}
    </button>

    <!-- Links for Email and Password Change -->
    <div class="d-flex justify-content-between mt-4">
      <a
        class="btn btn-outline-secondary btn-sm"
        href="{% url 'users:email_change' %}"
      >
        {% trans "change_email" %}
      </a>
      <a
        class="btn btn-outline-secondary btn-sm"
        href="{% url 'users:password_change' %}"
      >
        {% trans "change_password" %}
      </a>
    </div>
  </form>
</div>

<script src="{% static 'js/users/profile.js' %}"></script>

{% endblock %}

center_fsp/templates/users/signup.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/users/user-auth.css' %}">
{% endblock %}

{% block content %}

<div class="container">
  {% include "includes/user_form.html" with title=title submit_text=submit_text %}
</div>

{% endblock %}

center_fsp/templates/users/user_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{{ personal.username }}{% endblock %}

{% block content %}

<div class="container mt-5">
  <div class="row">
    <!-- Заголовок -->
    <div class="col-12 text-center mb-4">
      <h2>{% trans "Подробная информация о пользователе" %}</h2>
    </div>

    <!-- Карточка с информацией о пользователе -->
    <div class="col-md-8 offset-md-2">
      <div class="card shadow-lg">
        <div class="card-header text-center">
          <!-- Аватарка и имя пользователя -->
          <div class="d-flex justify-content-center align-items-center">
            <div class="ml-3">
              <img src="{% if personal.has_avatar %}{{personal.get_small_avatar }}{% else %}{% static 'img/default_user_avatar.jpg' %}{% endif %}" class="rounded-circle" alt="{{personal.first_name }} {{personal.last_name }}" style="width: 80px; height: 80px; object-fit: cover;">
              <h4 class="text-muted">{% trans "Профиль пользователя" %}</h4>
              <h3 class="mb-0">{{ personal.first_name }} {{ personal.last_name }}</h3>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="row mb-3">
            <div class="col-md-4">
              <strong>{% trans "Username:" %}</strong>
            </div>
            <div class="col-md-8">
              {{ personal.username }}
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-md-4">
              <strong>{% trans "Email:" %}</strong>
            </div>
            <div class="col-md-8">
              {{ personal.email }}
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-md-4">
              <strong>{% trans "Регион:" %}</strong>
            </div>
            <div class="col-md-8">
              {% if personal.region %}
                {{personal.region.name }}
              {% else %}
                {% trans "Регион не установлен" %}
              {% endif %}
            </div>
          </div>

          {% if user.is_superuser %}
          <form method="post" action="{% url 'users:update_user_region' personal.pk %}">
            {% csrf_token %}
            <div class="mb-3">
              {{ region_form.region }}
            </div>
            <button type="submit" class="btn btn-success mb-2">{% trans "Обновить регион" %}</button>
          </form>

          <form method="post" action="{% url 'users:remove_user_region' personal.pk %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger mb-2">{% trans "Удалить регион" %}</button>
          </form>
          {% endif %}

          <div class="text-center">
            <a href="{% url 'users:users' %}" class="btn btn-outline-primary">
              <i class="bi bi-arrow-left-circle"></i> {% trans "Назад к списку" %}
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}