center_fsp/center_fsp/urls.py
from django.conf import settings
import django.conf.urls.static
import django.contrib
import django.contrib.auth.urls
from django.urls import include, path

urlpatterns = [
    path("", include("homepage.urls")),
    path("calendar/", include("meropriations_calendar.urls")),
    path("meropriations/", include("meropriations.urls")),
    path("stats/", include("stats.urls")),
    path("feedback/", include("feedback.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("allauth.urls")),
    path("admin/", django.contrib.admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += django.conf.urls.static.static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT,
)

urlpatterns += django.conf.urls.static.static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

center_fsp/meropriations/urls.py
from django.urls import path
from django.views.generic import TemplateView

from meropriations import views

app_name = "meropriations"

urlpatterns = [
    path(
        "",
        views.MeropriationList.as_view(),
        name="meropriations",
    ),
    path(
        "<int:pk>/",
        views.MeropriationDetailView.as_view(),
        name="meropriation_detail",
    ),
    path(
        "new/",
        views.MeropriationCreateView.as_view(),
        name="meropriation_new",
    ),
    path(
        "results/new/",
        views.ResultCreateView.as_view(),
        name="results_new",
    ),
    path("add-team/", views.AddTeamView.as_view(), name="add_team"),
    path(
        "delete-participant/<int:participant_id>/",
        views.DeleteParticipantView.as_view(),
        name="delete_participant",
    ),
    path(
        "notifications/",
        views.Notifications.as_view(),
        name="notifications",
    ),
    path(
        "download-templates/",
        TemplateView.as_view(
            template_name="meropriations/download_templates.html",
        ),
        name="download_templates",
    ),
    path(
        "generate-result-report/<int:meropriation_id>/",
        views.GenerateResultReportView.as_view(),
        name="generate_result_report",
    ),
    path(
        "notifications/delete/<int:notification_id>/",
        views.DeleteNotificationView.as_view(),
        name="delete_notification",
    ),
]

center_fsp/stats/urls.py
from django.urls import path

from stats.views import (
    RegionStatisticsView,
    TeamStatisticsView,
    UserStatisticsView,
)

app_name = "stats"
urlpatterns = [
    path("regions/", RegionStatisticsView.as_view(), name="region_statistics"),
    path("users/", UserStatisticsView.as_view(), name="user_statistics"),
    path("teams/", TeamStatisticsView.as_view(), name="team_statistics"),
]

center_fsp/meropriations/models.py
__all__ = ()
import django.db.models
from django.utils.translation import gettext_lazy as _

import users.models


class Structure(django.db.models.Model):
    name = django.db.models.CharField(
        verbose_name="название",
        max_length=150,
        null=False,
        unique=True,
    )

    class Meta:
        ordering = ("name",)
        verbose_name = "состав"
        verbose_name_plural = "составы"

    def __str__(self):
        return self.name


class Tip(django.db.models.Model):
    name = django.db.models.CharField(
        verbose_name="название",
        max_length=150,
        null=False,
        unique=True,
    )

    class Meta:
        ordering = ("name",)
        verbose_name = "тип соревнования"
        verbose_name_plural = "типы соревнований"

    def __str__(self):
        return self.name


class Discipline(django.db.models.Model):
    name = django.db.models.CharField(
        verbose_name="название",
        max_length=150,
        null=False,
        unique=True,
    )

    class Meta:
        ordering = ("name",)
        verbose_name = "дисциплина"
        verbose_name_plural = "дисциплины"

    def __str__(self):
        return self.name


class Meropriation(django.db.models.Model):
    region = django.db.models.ForeignKey(
        users.models.Region,
        verbose_name="регион",
        null=True,
        on_delete=django.db.models.CASCADE,
        related_name="meropriation_regions",
    )
    is_published = django.db.models.BooleanField(
        verbose_name="опубликовано",
        default=False,
    )
    name = django.db.models.CharField(
        verbose_name="название",
        max_length=150,
        unique=False,
        null=True,
    )
    text = django.db.models.TextField(
        null=True,
        verbose_name="описание мероприятия",
    )
    count = django.db.models.PositiveIntegerField(
        null=True,
        verbose_name="количество участников",
    )
    place = django.db.models.TextField(
        null=True,
        verbose_name="место проведения",
    )
    structure = django.db.models.ForeignKey(
        Structure,
        verbose_name="состав",
        null=True,
        on_delete=django.db.models.CASCADE,
        related_name="meropriation_structures",
    )
    tip = django.db.models.ForeignKey(
        Tip,
        verbose_name="тип соревнования",
        null=True,
        on_delete=django.db.models.CASCADE,
        related_name="meropriation_tips",
    )
    disciplines = django.db.models.ManyToManyField(
        Discipline,
        verbose_name="дисциплины",
    )
    date_start = django.db.models.DateField(
        verbose_name="дата начала",
        null=True,
    )
    date_end = django.db.models.DateField(
        verbose_name="дата конца",
        null=True,
    )

    class Meta:
        ordering = ("name",)
        verbose_name = "мероприятие"
        verbose_name_plural = "мероприятия"

    def __str__(self):
        return self.name


class Team(django.db.models.Model):
    class Status(django.db.models.TextChoices):
        WINNER = _("winner")
        PRIZER = _("prizer")
        PARTICIPANT = _("participant")

    status = django.db.models.CharField(
        verbose_name="статус мероприятия",
        choices=Status.choices,
        default=Status.PARTICIPANT,
        max_length=30,
    )
    name = django.db.models.CharField(
        verbose_name="название",
        max_length=150,
        unique=False,
        null=True,
    )

    class Meta:
        ordering = ("name",)
        verbose_name = "команда"
        verbose_name_plural = "команды"

    def __str__(self):
        return self.name


class Participant(django.db.models.Model):
    name = django.db.models.CharField(
        verbose_name="фио",
        max_length=150,
        unique=False,
        null=True,
    )
    team = django.db.models.ForeignKey(
        Team,
        verbose_name="команда",
        on_delete=django.db.models.CASCADE,
        null=True,
        blank=True,
    )

    class Meta:
        ordering = ("team__name",)
        verbose_name = "участник"
        verbose_name_plural = "участники"

    def __str__(self):
        return self.name


class Result(django.db.models.Model):
    meropriation = django.db.models.ForeignKey(
        Meropriation,
        verbose_name="мероприятие",
        on_delete=django.db.models.CASCADE,
        null=True,
        blank=True,
    )
    team = django.db.models.ForeignKey(
        Team,
        verbose_name="команда",
        on_delete=django.db.models.CASCADE,
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = "результат"
        verbose_name_plural = "результаты"

    def __str__(self):
        return self.meropriation.name


class Notification(django.db.models.Model):
    meropriation = django.db.models.ForeignKey(
        Meropriation,
        verbose_name="мероприятие",
        on_delete=django.db.models.CASCADE,
        null=True,
        blank=True,
    )
    text = django.db.models.CharField(
        verbose_name="текст уведомления",
        max_length=150,
        null=False,
    )

    class Meta:
        verbose_name = "уведомление"
        verbose_name_plural = "уведомления"

    def __str__(self):
        return self.meropriation.name

center_fsp/meropriations/views.py
__all__ = ()
import csv

from allauth.core.internal.httpkit import redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
import django.forms
from django.http import HttpResponse
import django.shortcuts
from django.urls import reverse_lazy
import django.views.generic
from django.views.generic import DetailView, View
from django.views.generic.edit import CreateView

from meropriations.forms import MeropriationForm
from meropriations.models import (
    Meropriation,
    Notification,
    Participant,
    Result,
    Team,
)
from meropriations.parsers.parser_txt import parse_txt_file
from meropriations.parsers.parser_xlsx import parse_excel_file


class MeropriationList(LoginRequiredMixin, django.views.generic.ListView):
    template_name = "meropriations/list_meropriation.html"
    context_object_name = "meropriations"

    def get_queryset(self):
        region = self.request.user.region
        if self.request.user.is_staff:
            return Meropriation.objects.all()

        if not region:
            return Meropriation.objects.none()

        return Meropriation.objects.filter(region=region)


class MeropriationCreateView(LoginRequiredMixin, CreateView):
    model = Meropriation
    form_class = MeropriationForm
    template_name = "meropriations/meropriation_form.html"
    success_url = reverse_lazy("meropriations:meropriations")

    def form_valid(self, form):
        form.instance.region = self.request.user.region
        return super().form_valid(form)


class MeropriationDetailView(LoginRequiredMixin, DetailView):
    model = Meropriation
    template_name = "meropriations/meropriation_detail.html"
    context_object_name = "meropriation"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):
        meropriation = self.get_object()
        url = reverse_lazy(
            "meropriations:meropriation_detail",
            kwargs={"pk": meropriation.pk},
        )

        if not request.user.is_superuser:
            messages.error(
                request,
                "Вы не загрузили файлы. "
                "Убедитесь, что выбран хотя бы один файл.",
            )
            return redirect(url)

        last_status = (
            "Опубликован" if meropriation.is_published else "Не опубликован"
        )
        meropriation.is_published = not meropriation.is_published
        now_status = (
            "Опубликован" if meropriation.is_published else "Не опубликован"
        )

        meropriation.save()
        Notification.objects.create(
            meropriation=meropriation,
            text=f"Статус изменен с '{last_status}' на '{now_status}'",
        )
        messages.success(request, "Статус успешно обновлен!")
        return redirect(url)


class ResultCreateView(LoginRequiredMixin, CreateView):
    template_name = "meropriations/new_results.html"

    def get(self, request):
        user_region = self.request.user.region
        if not user_region:
            return django.shortcuts.redirect("meropriations:meropriations")

        meropriations = Meropriation.objects.filter(
            region=user_region,
            is_published=True,
        )

        return django.shortcuts.render(
            request,
            "meropriations/new_results.html",
            {
                "meropriations": meropriations,
                "title": "Загрузка",
            },
        )

    def post(self, request):
        user_region = self.request.user.region
        if not user_region:
            return django.shortcuts.redirect("meropriations:meropriations")

        meropriations = Meropriation.objects.filter(
            region=user_region,
            is_published=True,
        )

        meropriation_id = request.POST.get("meropriation")
        try:
            meropriation = Meropriation.objects.get(id=meropriation_id)
        except Meropriation.DoesNotExist:
            messages.error(request, "Выбранное мероприятие некорректно.")
            return django.shortcuts.redirect("meropriations:results_new")

        files = request.FILES.getlist("file")
        if not files:
            messages.error(request, "Вы не загрузили файлы.")
            return django.shortcuts.redirect("meropriations:results_new")

        teams = Team.objects.filter(result__meropriation_id=meropriation_id)
        for team in teams:
            team.delete()

        Result.objects.filter(meropriation_id=meropriation_id).delete()

        for uploaded_file in files:
            if uploaded_file.name.endswith(
                ".xlsx",
            ) or uploaded_file.name.endswith(".xls"):
                parse_excel_file(uploaded_file, meropriation.id)
            elif uploaded_file.name.endswith(
                ".txt",
            ) or uploaded_file.name.endswith(".csv"):
                parse_txt_file(uploaded_file, meropriation.id)
            else:
                messages.error(
                    request,
                    "Неподдерживаемый тип файла: {}".format(
                        uploaded_file.name,
                    ),
                )
                return django.shortcuts.redirect("meropriations:results_new")

        results = Result.objects.filter(meropriation=meropriation).all()

        if not results:
            messages.error(request, "Нет результатов")
            return django.shortcuts.redirect("meropriations:results_new")

        teams = [result.team for result in results if result.team]

        participants = Participant.objects.filter(team__in=teams).distinct()

        messages.success(request, "Файлы успешно загружены и обработаны.")
        return django.shortcuts.render(
            request,
            "meropriations/new_results.html",
            {
                "uploaded": True,
                "meropriations": meropriations,
                "participants": participants,
                "title": "Загрузка",
            },
        )


class AddTeamView(View):
    def post(self, request):
        meropriation_id = request.POST.get("meropriation")
        team_name = request.POST.get("team_name")

        if not meropriation_id or not team_name:
            messages.error(
                request,
                "Ошибка: все поля обязательны для заполнения.",
            )
            return django.shortcuts.redirect("meropriations:add_team")

        try:
            meropriation = Meropriation.objects.get(id=meropriation_id)
        except Meropriation.DoesNotExist:
            messages.error(request, "Выбранное мероприятие некорректно.")
            return django.shortcuts.redirect("meropriations:add_team")

        Team.objects.create(name=team_name)

        messages.success(
            request,
            f"Команда '{team_name}' успешно добавлена на мероприятие "
            f"'{meropriation.name}'",
        )
        return django.shortcuts.redirect("meropriations:results_new")


class DeleteParticipantView(View):
    def post(self, request, participant_id):
        try:
            participant = Participant.objects.get(id=participant_id)
            participant.delete()
            messages.success(request, "Участник успешно удален.")
        except Participant.DoesNotExist:
            messages.error(request, "Участник не найден.")

        return django.shortcuts.redirect("meropriations:results_new")


class GenerateResultReportView(DetailView):
    def get(self, request, *args, **kwargs):
        meropriation_id = kwargs.get("meropriation_id")

        try:
            meropriation = Meropriation.objects.get(id=meropriation_id)
        except Meropriation.DoesNotExist:
            return HttpResponse(status=404, content="Мероприятие не найдено.")

        all_teams = Team.objects.filter(
            result__meropriation=meropriation,
        ).order_by("-status")
        winners = Team.objects.filter(
            result__meropriation=meropriation,
            status="WINNER",
        ).count()
        prizers = Team.objects.filter(
            result__meropriation=meropriation,
            status="PRIZER",
        ).count()
        participants = all_teams.count() - winners - prizers

        response = HttpResponse(content_type="text/csv")
        response["Content-Disposition"] = (
            f'attachment; filename="result_report_{meropriation_id}.csv"'
        )

        writer = csv.writer(response)

        writer.writerow(["Статистика", "Количество"])
        writer.writerow(["Победителей", winners])
        writer.writerow(["Призёров", prizers])
        writer.writerow(["Участников", participants])
        writer.writerow(["Общее количество участников", all_teams.count()])

        writer.writerow([])

        writer.writerow(["Команда", "Статус"])
        for team in all_teams:
            status = "участник"
            if team.status == "PRIZER":
                status = "призер"
            elif team.status == "WINNER":
                status = "победитель"

            writer.writerow([team.name, status])

        return response


class Notifications(LoginRequiredMixin, django.views.generic.ListView):
    template_name = "meropriations/notifications.html"
    context_object_name = "notifications"

    def get_queryset(self):
        region = self.request.user.region
        if not region:
            return django.shortcuts.redirect("homepage:main")

        return Notification.objects.filter(meropriation__region=region)


class DeleteNotificationView(LoginRequiredMixin, View):
    def post(self, request, notification_id):
        notification = django.shortcuts.get_object_or_404(
            Notification,
            id=notification_id,
        )
        notification.delete()

        return redirect("meropriations:notifications")

center_fsp/templates/meropriations/download_templates.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Скачать шаблоны" %}{% endblock %}

{% block content %}
<div class="container mt-5">
  <h2 class="text-center">{% trans "Скачать шаблоны файлов" %}</h2>
  <p class="text-muted text-center mb-4">{% trans "Выберите подходящий формат для загрузки шаблона." %}</p>

  <div class="row justify-content-center">
    <div class="col-md-6">
      <ul class="list-group">
        <li class="list-group-item d-flex align-items-center">
          <i class="bi bi-file-earmark-excel-fill text-success me-3" style="font-size: 1.5rem;"></i>
          <a href="{% static 'templates/results_template.xlsx' %}" class="text-decoration-none" download>
            {% trans "Шаблон Excel (.xlsx)" %}
          </a>
        </li>
        <li class="list-group-item d-flex align-items-center">
          <i class="bi bi-file-earmark-text-fill text-primary me-3" style="font-size: 1.5rem;"></i>
          <a href="{% static 'templates/results_template.txt' %}" class="text-decoration-none" download>
            {% trans "Шаблон текстовый (.txt)" %}
          </a>
        </li>
        <li class="list-group-item d-flex align-items-center">
          <i class="bi bi-file-earmark-spreadsheet-fill text-info me-3" style="font-size: 1.5rem;"></i>
          <a href="{% static 'templates/results_template.csv' %}" class="text-decoration-none" download>
            {% trans "Шаблон CSV (.csv)" %}
          </a>
        </li>
        <li class="list-group-item d-flex align-items-center">
          <i class="bi bi-file-earmark-excel-fill text-success me-3" style="font-size: 1.5rem;"></i>
          <a href="{% static 'templates/results_template.xls' %}" class="text-decoration-none" download>
            {% trans "Шаблон Excel старый (.xls)" %}
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

center_fsp/templates/meropriations/list_meropriation.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Мероприятия" %}{% endblock %}

{% block content %}

<div class="container my-5">
  <h2 class="text-center text-primary mb-4">{% trans "Все мероприятия" %}</h2>

  {% if meropriations %}
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
      {% for meropriation in meropriations %}
        <div class="col">
          <div class="card h-100 shadow-sm">
            <div class="card-body">
              <h5 class="card-title text-primary">{{ meropriation.name }}</h5>
              <p class="card-text text-muted">{{ meropriation.place }}</p>
              <p class="card-text text-muted">{{ meropriation.normal_place }}</p>
              {% if meropriation.is_published %}
                <p class="badge bg-success">{% trans "Мероприятие опубликовано" %}</p>
              {% else %}
                <p class="badge bg-danger">{% trans "Мероприятие не опубликовано" %}</p>
              {% endif %}
            </div>
            <div class="card-footer text-end">
              <a href="{% url 'meropriations:meropriation_detail' meropriation.pk %}" class="btn btn-outline-primary btn-sm" style="margin-bottom: 15px;">
                {% trans "Подробнее" %}
              </a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <p class="text-center text-muted">{% trans "Нет мероприятий" %}</p>
  {% endif %}
  {% if not user.is_staff %}
    <div class="mt-4 text-center">
      <a href="{% url 'meropriations:meropriation_new' %}" class="btn btn-primary">
        {% trans "Добавить мероприятие" %}
      </a>
    </div>
  {% endif %}
</div>

{% endblock %}

center_fsp/templates/meropriations/meropriation_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{{ meropriation.name }}{% endblock %}

{% block content %}
<div class="container my-5">
  <div class="card shadow-lg">
    <div class="card-header bg-primary text-white">
      <h2>{{ meropriation.name }}</h2>
    </div>
    <div class="card-body">
      <p><strong>{% trans "Описание:" %}</strong></p>
      <p>{{ meropriation.text }}</p>

      {% if meropriation.is_published %}
        <p class="badge bg-success">{% trans "Мероприятие опубликовано" %}</p>
      {% else %}
        <p class="badge bg-danger">{% trans "Мероприятие не опубликовано" %}</p>
      {% endif %}
      <p><strong>{% trans "Адрес:" %}</strong> {{ meropriation.place }}</p>

      <!-- Вывод дисциплин в виде списка -->
      <p><strong>{% trans "Дисциплины:" %}</strong></p>
      {% if meropriation.disciplines.all %}
        <ul class="list-group mb-3">
          {% for discipline in meropriation.disciplines.all %}
            <li class="list-group-item">{{ discipline.name }}</li>
          {% endfor %}
        </ul>
      {% else %}
        <p class="text-muted">{% trans "Дисциплины отсутствуют." %}</p>
      {% endif %}

      <p><strong>{% trans "Количество участников:" %}</strong> {{ meropriation.count }}</p>
      <p><strong>{% trans "Дата начала:" %}</strong> {{ meropriation.date_start|date:"d.m.Y" }}</p>
      <p><strong>{% trans "Дата окончания:" %}</strong> {{ meropriation.date_end|date:"d.m.Y" }}</p>
    </div>
    <div class="card-footer text-end">
      <a href="{% url 'meropriations:meropriations' %}" class="btn btn-outline-secondary">{% trans "Назад к списку" %}</a>
    </div>
  </div>

  {% if user.is_superuser %}
    <div class="card mt-4">
      <div class="card-header bg-warning">
        <h5>{% trans "Изменить статус мероприятия" %}</h5>
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          <div class="form-group">
            <button type="submit" class="btn {% if meropriation.is_published %}btn-danger{% else %}btn-success{% endif %}">
              {% if meropriation.is_published %}
                {% trans "Снять с публикации" %}
              {% else %}
                {% trans "Опубликовать" %}
              {% endif %}
            </button>
          </div>
        </form>
      </div>
    </div>
  {% endif %}

  {% if meropriation.result_set.exists %}
    <div class="card mt-5">
      <div class="card-header bg-success text-white">
        <h5>{% trans "Результаты мероприятия" %}</h5>
      </div>
      <div class="card-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>{% trans "Название команды" %}</th>
              <th>{% trans "Статус" %}</th>
              <th>{% trans "Участники" %}</th>
            </tr>
          </thead>
          <tbody>
            {% for result in meropriation.result_set.all %}
              <tr>
                <td>{{ result.team.name }}</td>
                <td>{{ result.team.status }}</td>
                <td>
                  {% for participant in result.team.participant_set.all %}
                    {{ participant.name }}{% if not forloop.last %}, {% endif %}
                  {% endfor %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <a href="{% url 'meropriations:generate_result_report' meropriation.pk %}" class="btn btn-success">Скачать протокол соревнования</a>
    </div>
  {% else %}
    <p class="mt-4 text-muted">{% trans "Результаты пока не добавлены." %}</p>
  {% endif %}
</div>
{% endblock %}

center_fsp/templates/meropriations/new_results.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}Загрузка{% endblock %}

{% block content %}

<div class="container mt-5">
  <h2 class="text-center mb-4">{% trans "Мультизагрузчик результатов соревнований" %}</h2>

  <div class="alert alert-warning text-center mb-4">
    {% trans "Подходят только форматы .xlsx .txt .csv .xls. Шаблон файла результатов: " %}
    <a href="{% url 'meropriations:download_templates' %}" class="btn btn-link">{% trans "Скачать шаблон" %}</a>
  </div>

  {% if not uploaded %}
    <!-- Форма для выбора мероприятия и загрузки данных -->
    <div class="card mb-4">
      <div class="card-header bg-success text-white text-center">
        {% trans "Выберите мероприятие и загрузите файлы" %}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="mb-3">
            <label for="meropriation" class="form-label">{% trans "Выберите мероприятие" %}</label>
            <select name="meropriation" class="form-select" required>
              {% for item in meropriations %}
                <option value="{{ item.id }}">{{ item.name }}</option>
              {% endfor %}
            </select>
          </div>

          <div class="mb-3">
            <label for="files" class="form-label">{% trans "Загрузите файлы" %}</label>
            <input type="file" name="file" multiple class="form-control" required>
          </div>

          <div class="text-center">
            <button type="submit" class="btn btn-success mt-2 px-4">{% trans "Загрузить" %}</button>
          </div>
        </form>
      </div>
    </div>
  {% else %}
    <div class="alert alert-success text-center mb-4">
      {% trans "Файлы и мероприятие успешно загружены." %}
    </div>
  {% endif %}

  <!-- Информация об участниках и командах -->
  {% if participants %}
    <div class="card mb-4">
      <div class="card-header bg-info text-white text-center">
        {% trans "Списки команд и участников" %}
      </div>
      <div class="card-body">
        <div class="accordion" id="teamsAccordion">
          {% for participant in participants %}
            {% ifchanged participant.team.id %}
              <div class="accordion-item">
                <h2 class="accordion-header" id="heading{{ forloop.counter }}">
                  <button class="accordion-button" type="button" data-bs-toggle="collapse"
                          data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="true"
                          aria-controls="collapse{{ forloop.counter }}">
                    {{ participant.team.name }}
                  </button>
                </h2>
                <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse show" aria-labelledby="heading{{ forloop.counter }}"
                     data-bs-parent="#teamsAccordion">
                  <div class="accordion-body">
                    <ul class="list-group">
                      {% for p in participants %}
                        {% if p.team and p.team.id == participant.team.id %}
                          <li class="list-group-item d-flex justify-content-between align-items-center">
                            {{ p.name }}
                          </li>
                        {% endif %}
                      {% endfor %}
                    </ul>
                  </div>
                </div>
              </div>
            {% endifchanged %}
          {% endfor %}
        </div>
      </div>
    </div>
  {% endif %}
</div>

{% endblock %}

center_fsp/templates/meropriations/notifications.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Уведомления" %}{% endblock %}

{% block content %}

<div class="container mt-4">
  <h2 class="mb-4 text-center text-primary">
    <i class="bi bi-bell-fill"></i> {% trans "Уведомления" %}
  </h2>

  {% if notifications %}
    <div class="row row-cols-1 row-cols-md-2 g-4">
      {% for notification in notifications %}
        <div class="col">
          <div class="card shadow-sm border-0">
            <div class="card-body">
              <h5 class="card-title text-primary">
                <i class="bi bi-calendar-check me-2"></i>{{ notification.meropriation }}
              </h5>
              <p class="card-text text-muted">
                {{ notification.text }}
              </p>
            </div>
            <div class="card-footer text-muted small text-end">
              <i class="bi bi-clock me-1"></i>{{ notification.created_at|date:"d.m.Y H:i" }}
              <form method="post" action="{% url 'meropriations:delete_notification' notification.id %}" class="d-inline">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-sm ms-2">
                  <i class="bi bi-bookmark-check"></i> {% trans "Прочитано" %}
                </button>
              </form>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <div class="alert alert-info text-center mt-4" role="alert">
      <i class="bi bi-info-circle"></i> {% trans "Уведомлений нет" %}
    </div>
  {% endif %}
</div>

{% endblock %}