center_fsp/center_fsp/urls.py
from django.conf import settings
import django.conf.urls.static
import django.contrib
import django.contrib.auth.urls
from django.urls import include, path

urlpatterns = [
    path("", include("homepage.urls")),
    path("calendar/", include("meropriations_calendar.urls")),
    path("meropriations/", include("meropriations.urls")),
    path("stats/", include("stats.urls")),
    path("feedback/", include("feedback.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("allauth.urls")),
    path("admin/", django.contrib.admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += django.conf.urls.static.static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT,
)

urlpatterns += django.conf.urls.static.static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

center_fsp/feedback/urls.py
from django.urls import path

from feedback import views

app_name = "feedback"
urlpatterns = [
    path(
        "",
        views.FeedbackForm.as_view(),
        name="feedback",
    ),
    path(
        "feedbacks/",
        views.FeedbackList.as_view(),
        name="feedbacks",
    ),
]

center_fsp/homepage/urls.py
from django.urls import path

import homepage.views

app_name = "homepage"
urlpatterns = [
    path("", homepage.views.Home.as_view(), name="main"),
]

center_fsp/meropriations/urls.py
from django.urls import path
from django.views.generic import TemplateView

from meropriations import views

app_name = "meropriations"

urlpatterns = [
    path(
        "",
        views.MeropriationList.as_view(),
        name="meropriations",
    ),
    path(
        "<int:pk>/",
        views.MeropriationDetailView.as_view(),
        name="meropriation_detail",
    ),
    path(
        "new/",
        views.MeropriationCreateView.as_view(),
        name="meropriation_new",
    ),
    path(
        "results/new/",
        views.ResultCreateView.as_view(),
        name="results_new",
    ),
    path("add-team/", views.AddTeamView.as_view(), name="add_team"),
    path(
        "delete-participant/<int:participant_id>/",
        views.DeleteParticipantView.as_view(),
        name="delete_participant",
    ),
    path(
        "notifications/",
        views.Notifications.as_view(),
        name="notifications",
    ),
    path(
        "download-templates/",
        TemplateView.as_view(
            template_name="meropriations/download_templates.html",
        ),
        name="download_templates",
    ),
    path(
        "generate-result-report/<int:meropriation_id>/",
        views.GenerateResultReportView.as_view(),
        name="generate_result_report",
    ),
    path(
        "notifications/delete/<int:notification_id>/",
        views.DeleteNotificationView.as_view(),
        name="delete_notification",
    ),
]

center_fsp/meropriations_calendar/urls.py
from django.urls import path

import meropriations_calendar.views

app_name = "calendar"
urlpatterns = [
    path("", meropriations_calendar.views.Home.as_view(), name="main"),
    path(
        "detail/<int:event_id>/",
        meropriations_calendar.views.event_detail,
        name="detail_event",
    ),
    path(
        "results/<int:event_id>/",
        meropriations_calendar.views.event_results,
        name="event_results",
    ),
]

center_fsp/stats/urls.py
from django.urls import path

from stats.views import (
    RegionStatisticsView,
    TeamStatisticsView,
    UserStatisticsView,
)

app_name = "stats"
urlpatterns = [
    path("regions/", RegionStatisticsView.as_view(), name="region_statistics"),
    path("users/", UserStatisticsView.as_view(), name="user_statistics"),
    path("teams/", TeamStatisticsView.as_view(), name="team_statistics"),
]

center_fsp/users/urls.py
from allauth.account.views import ConfirmEmailView
from allauth.account.views import EmailVerificationSentView
from allauth.account.views import EmailView
from allauth.account.views import LoginView
from allauth.account.views import LogoutView
from allauth.account.views import PasswordChangeView
from allauth.account.views import PasswordResetDoneView
from allauth.account.views import PasswordResetFromKeyDoneView
from allauth.account.views import PasswordResetFromKeyView
from allauth.account.views import PasswordResetView
from django.urls import path, re_path, reverse_lazy

from users import forms
from users import views

app_name = "users"

urlpatterns = [
    path(
        "account/",
        views.AccountView.as_view(),
        name="profile",
    ),
    path(
        "signup/",
        views.RegionalRepresentativeSignupView.as_view(),
        name="signup",
    ),
    path(
        "login/",
        LoginView.as_view(
            form_class=forms.LoginForm,
            template_name="users/login.html",
        ),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path(
        "confirm-email/",
        EmailVerificationSentView.as_view(
            template_name="users/confirm_email.html",
        ),
        name="confirm_email",
    ),
    re_path(
        r"^confirm-email/(?P<key>[-:\w]+)/$",
        ConfirmEmailView.as_view(
            template_name="users/confirm_email_from_sent.html",
        ),
        name="account_confirm_email",
    ),
    path(
        "email/",
        EmailView.as_view(
            form_class=forms.EmailForm,
            template_name="users/email_change.html",
        ),
        name="email_change",
    ),
    path(
        "password/change/",
        PasswordChangeView.as_view(
            form_class=forms.ChangePasswordForm,
            template_name="users/password_change.html",
            success_url=reverse_lazy("users:password_change_done"),
        ),
        name="password_change",
    ),
    path(
        "password/change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password/reset/",
        PasswordResetView.as_view(
            form_class=forms.ResetPasswordForm,
            template_name="users/password_reset.html",
        ),
        name="password_reset",
    ),
    path(
        "password/reset/done/",
        PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    re_path(
        r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        PasswordResetFromKeyView.as_view(
            form_class=forms.ResetPasswordKeyForm,
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "password/reset/key/done/",
        PasswordResetFromKeyDoneView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path(
        "users/",
        views.UsersView.as_view(),
        name="users",
    ),
    path(
        "users/<int:pk>/",
        views.UserDetailView.as_view(),
        name="user_detail",
    ),
    path(
        "<int:pk>/update-region/",
        views.update_user_region,
        name="update_user_region",
    ),
    path(
        "<int:pk>/remove-region/",
        views.remove_user_region,
        name="remove_user_region",
    ),
]

center_fsp/users/models.py
__all__ = ()
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from sorl.thumbnail import delete, get_thumbnail


class Region(models.Model):
    name = models.CharField(
        verbose_name="регион",
        max_length=150,
        null=True,
    )

    class Meta:
        ordering = ("name",)
        verbose_name = "регион"
        verbose_name_plural = "регионы"

    def __str__(self):
        return self.name


class User(AbstractUser):
    avatar = models.ImageField(
        _("avatar"),
        upload_to="avatars/",
        null=True,
        blank=True,
    )
    region = models.ForeignKey(
        Region,
        verbose_name="регион",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )

    def has_avatar(self):
        return self.avatar and self.avatar.url is not None

    def get_small_avatar(self):
        return get_thumbnail(self.avatar, "80", crop="center").url

    def get_large_avatar(self):
        return get_thumbnail(self.avatar, "200", crop="center").url

    def save(self, *args, **kwargs):
        try:
            old = User.objects.get(pk=self.pk)
            if old.has_avatar() and not self.has_avatar():
                delete(old.avatar)
        except User.DoesNotExist:
            pass

        super().save(*args, **kwargs)

    class Meta:
        ordering = ("region",)
        verbose_name = "пользователь"
        verbose_name_plural = "пользователи"

    def __str__(self):
        return self.username

center_fsp/users/forms.py
__all__ = ()
from allauth.account.forms import (
    AddEmailForm,
    ChangePasswordForm,
    LoginForm,
    ResetPasswordForm,
    ResetPasswordKeyForm,
    SignupForm,
)
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm
from django.utils.translation import gettext_lazy as _

from users.models import Region, User


class BootstrapFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if len(self.visible_fields()) == 1:
            self.visible_fields()[0].field.widget.attrs[
                "class"
            ] = "form-control input-field-only-one"
        else:
            for field in self.visible_fields():
                field.field.widget.attrs["class"] = "form-control input-field"
                if isinstance(field.field.widget, forms.CheckboxInput):
                    field.field.widget.attrs["class"] = "form-check-input"

        self.update_errors_class()

    def update_errors_class(self):
        for field in self.visible_fields():
            if self.errors.get(field.name):
                if "is-invalid" not in field.field.widget.attrs["class"]:
                    field.field.widget.attrs["class"] += " is-invalid"

    def add_error(self, field, error):
        super().add_error(field, error)
        self.update_errors_class()


class UserForm(BootstrapFormMixin, UserChangeForm):
    password = None

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields[User.email.field.name].widget.attrs["readonly"] = True
        self.fields[User.email.field.name].widget.attrs["disabled"] = True
        self.fields[User.avatar.field.name].widget.attrs["class"] += " d-none"

    class Meta(UserChangeForm.Meta):
        model = get_user_model()

        fields = [
            User.username.field.name,
            User.email.field.name,
            User.avatar.field.name,
        ]


class UserRegionForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["region"]
        widgets = {"region": forms.Select(attrs={"class": "form-control"})}


class RegionalRepresentativeSignupForm(BootstrapFormMixin, SignupForm):
    def __init__(self, *args, **kwargs):
        kwargs.pop("instance", None)
        super().__init__(*args, **kwargs)

    def save(self, request):
        user = super().save(request)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.region = self.cleaned_data["region"]
        user.save()
        return user

    region = forms.ModelChoiceField(
        queryset=Region.objects.all(),
        required=True,
        label=_("Region"),
        widget=forms.Select(attrs={"class": "form-select"}),
    )
    first_name = forms.CharField(
        required=True,
        label=_("First Name"),
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": _("Enter your first name"),
            },
        ),
    )
    last_name = forms.CharField(
        required=True,
        label=_("Last Name"),
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": _("Enter your last name"),
            },
        ),
    )


class EmailForm(BootstrapFormMixin, AddEmailForm):
    pass


class LoginForm(BootstrapFormMixin, LoginForm):
    pass


class ChangePasswordForm(BootstrapFormMixin, ChangePasswordForm):
    pass


class ResetPasswordForm(BootstrapFormMixin, ResetPasswordForm):
    pass


class ResetPasswordKeyForm(BootstrapFormMixin, ResetPasswordKeyForm):
    pass

center_fsp/users/views.py
__all__ = ()
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import translation
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
import django.views.generic
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, FormView

from users.forms import (
    RegionalRepresentativeSignupForm,
    UserForm,
    UserRegionForm,
)
from users.models import User


class AccountView(LoginRequiredMixin, FormView):
    template_name = "users/profile.html"
    form_class = UserForm

    def get_initial(self):
        return {
            "username": self.request.user.username,
            "email": self.request.user.email,
            "avatar": self.request.user.avatar,
        }

    def post(self, request, *args, **kwargs):
        post = request.POST.copy()
        post["email"] = request.user.email
        user_form = UserForm(post, request.FILES, instance=request.user)
        new_username = user_form.cleaned_data.get("username")

        if new_username != request.user.username:
            if user_form.is_valid():
                if User.objects.filter(username=new_username).exists():
                    user_form.add_error(
                        "username",
                        _("username_is_already_taken"),
                    )
        elif user_form.is_valid():
            user_form.save()
            return redirect("users:profile")

        return render(request, "users/profile.html", {"form": user_form})


class PasswordChangeDoneView(views.PasswordChangeDoneView):
    pass


@method_decorator(staff_member_required, name="dispatch")
class RegionalRepresentativeSignupView(CreateView):
    model = User
    form_class = RegionalRepresentativeSignupForm
    template_name = "users/signup.html"

    def get(self, request, *args, **kwargs):
        translation.activate(request.LANGUAGE_CODE)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Добавляем переводы для заголовка и кнопки
        context["title"] = _("Register Regional Representative")
        context["submit_text"] = _("Register")
        return context

    def form_valid(self, form):
        user = form.save(request=self.request)
        user.first_name = form.cleaned_data["first_name"]
        user.last_name = form.cleaned_data["last_name"]
        user.region = form.cleaned_data["region"]
        user.is_staff = False
        user.save()
        return redirect("users:users")


@method_decorator(staff_member_required, name="dispatch")
class UsersView(django.views.generic.ListView):
    template_name = "users/list_users.html"
    context_object_name = "users"
    queryset = User.objects.exclude(is_superuser=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Представители"
        return context


class UserDetailView(DetailView):
    model = User
    template_name = "users/user_detail.html"
    context_object_name = "personal"

    def get_object(self, queryset=None):
        return get_object_or_404(User, pk=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Проверяем, является ли текущий пользователь суперюзером
        if self.request.user.is_superuser:
            context["region_form"] = UserRegionForm(instance=self.object)

        return context


# Обработка изменения региона пользователя
def update_user_region(request, pk):
    user = get_object_or_404(User, pk=pk)

    # Проверяем, является ли текущий пользователь суперюзером
    if not request.user.is_superuser:
        messages.error(request, "У вас нет прав на выполнение этого действия.")
        return redirect("users:user_detail", pk=pk)

    if request.method == "POST":
        form = UserRegionForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, "Регион пользователя успешно обновлен.")
        else:
            messages.error(request, "Ошибка при обновлении региона.")

    return redirect("users:user_detail", pk=pk)


# Обработка удаления региона
def remove_user_region(request, pk):
    user = get_object_or_404(User, pk=pk)

    # Проверяем права суперюзера
    if not request.user.is_superuser:
        messages.error(request, "У вас нет прав на выполнение этого действия.")
        return redirect("users:user_detail", pk=pk)

    user.region = None
    user.save()
    messages.success(request, "Регион был успешно удален.")
    return redirect("users:user_detail", pk=pk)

center_fsp/templates/includes/footer.html
{% load i18n %}

<footer class="footer mt-auto py-3">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h5>{% trans "О нас" %}</h5>
        <p>&copy; {% trans "Центр спортивного программирования - мы определяем будущее" %}</p>
      </div>
      <div class="col-md-6">
        <h5>{% trans "Контакты" %}</h5>
        <a href="mailto:liceistykfu@gmail.com">{% trans "Email" %}: liceistykfu@gmail.com</a>
      </div>
    </div>
  </div>
</footer>

center_fsp/templates/includes/header.html
{% load static %}
{% load active_link_tags %}
{% load i18n %}

<header>
  <div class="container d-flex justify-content-between align-items-center py-3">
    <a href="{% url 'homepage:main' %}" class="logo d-flex align-items-center">
      <img src="{% static 'img/logo.svg' %}" alt="Logo" height="40">
      <span class="ms-2 fw-bold">{% trans "FSP Center" %}</span>
    </a>
    <nav class="my-auto nav-item dropdown">
      <a href="{% url 'homepage:main' %}" class="{% if view_name == 'homepage:main' %}active{% endif %}">{% trans "Главная" %}</a>
      <a href="{% url 'calendar:main' %}" class="{% if view_name == 'calendar:main' %}active{% endif %}">{% trans "Календарь мероприятий" %}</a>
      <a href="{% url 'stats:region_statistics' %}" class="{% if view_name == 'stats:region_statistics' %}active{% endif %}">{% trans "Аналитика" %}</a>
      <a href="{% url 'feedback:feedback' %}" class="{% if view_name == 'feedback:feedback' %}active{% endif %}">{% trans "Обратная связь" %}</a>
    </nav>
    <nav class="d-flex collapse" id="main-nav">
      <nav class="my-auto nav-item dropdown me-2">
        <button class="btn border-0 dropdown-toggle d-flex align-items-center" id="language-dropdown" type="button" aria-expanded="false" data-bs-toggle="dropdown" data-bs-display="static" aria-label="Toggle language">
          <i class="bi bi-globe me-2"></i>
          <span class="d-none d-lg-block" id="language-text">{% get_current_language as LANGUAGE_CODE %}{{ LANGUAGE_CODE|language_name_translated }}</span>
        </button>
        <ul class="dropdown-menu dropend" aria-labelledby="language-text" data-bs-popper="static">
          {% get_available_languages as LANGUAGES %}
          {% for lang_code, lang_name in LANGUAGES %}
            <li>
              <form action="{% url 'set_language' %}" method="post" class="d-inline">
                {% csrf_token %}
                <input type="hidden" name="language" value="{{ lang_code }}">
                <button type="submit" class="dropdown-item language-button d-flex align-items-center {% if lang_code == LANGUAGE_CODE %}active{% endif %}" aria-pressed="{% if lang_code == LANGUAGE_CODE %}true{% else %}false{% endif %}">
                  <i class="bi bi-globe me-2"></i>
                  {{ lang_name }}
                </button>
              </form>
            </li>
          {% endfor %}
          </ul>
      </nav>
      <nav class="my-auto nav-item dropdown">
        <button class="btn border-0 dropdown-toggle d-flex align-items-center" id="theme-dropdown" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i id="theme-icon-active" class="bi bi-sun-fill"></i>
          <span>{% trans "theme" %}</span>
        </button>
        <ul class="dropdown-menu">
          <li>
            <button class="dropdown-item" data-bs-theme-value="light">{% trans "light" %}</button>
          </li>
          <li>
            <button class="dropdown-item" data-bs-theme-value="dark">{% trans "dark" %}</button>
          </li>
        </ul>
      {% if request.resolver_match.view_name != 'users:login' %}
        {% if request.user.is_authenticated %}
          {% trans "no_user" as no_user %}
          <div class="dropdown ms-2">
            <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="{% if request.user.has_avatar %}{{ request.user.get_small_avatar }}{% else %}{% static 'img/default_user_avatar.jpg' %}{% endif %}" alt="{{ request.user.username }}" class="rounded-circle" width="48" height="48">
              <strong>{{ request.user.username|default:no_user }}</strong>
            </a>
            <ul class="dropdown-menu text-small">
              <li><a class="dropdown-item" {% if view_name != "users:profile" %}href="{% url 'users:profile' %}"{% endif %}>{% trans "my_profile" %}</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a href="{% url 'meropriations:meropriations' %}" class="dropdown-item">
                {% trans "meropriations" %}
              </a></li>
              {% if request.user.is_staff %}
                <li><a href="{% url 'users:users' %}" class="dropdown-item">
                  {% trans "users" %}
                </a></li>
                <li><a href="{% url 'feedback:feedbacks' %}" class="dropdown-item">
                  {% trans "feedbacks" %}
                </a></li>
                <li><a href="{% url 'admin:index' %}" class="dropdown-item">
                  {% trans "admin_panel" %}
                </a></li>
              {% else %}
                <li><a href="{% url 'meropriations:results_new' %}" class="dropdown-item">
                  {% trans "results" %}
                </a></li>
                <li><a href="{% url 'meropriations:notifications' %}" class="dropdown-item">
                  {% trans "notifications" %}
                </a></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'users:logout' %}">{% trans "exit" %}</a></li>
            </ul>
          </div>
        {% else %}
          <a href="{% url 'users:login' %}" class="btn btn-outline my-auto me-2">
            {% trans "sign_in" %}
          </a>
        {% endif %}
      {% endif %}
      </nav>
    </nav>
  </div>
</header>

center_fsp/templates/includes/user_form.html
{% load static %}
{% load i18n %}

{% with request.resolver_match.view_name as view_name %}
  <form method="POST" class="form-user-auth mt-5" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="d-flex flex-column col-10 col-sm-8 col-md-6 col-lg-5 col-xl-4 col-xxl-3 ms-auto me-auto">
      <h1 class="h3 mb-4 fw-bold text-center text-primary">{{ title }}</h1>

      <!-- Поля ввода -->
      <div class="form-group d-flex flex-column gap-3">
        {% for field in form %}
          {% if field.field.widget.input_type != "checkbox" %}
            <div class="form-floating">
              {{ field }}
              <label for="{{ field.id_for_label }}">
                {% if view_name == "users:login" and field.name == "login" %}
                  {% trans "Имя пользователя" %}
                {% else %}
                  {{ field.label }}
                {% endif %}
              </label>
              {% if field.errors %}
                <div class="invalid-feedback">
                  {{ field.errors|first }}
                </div>
              {% endif %}
            </div>
          {% endif %}
        {% endfor %}
        {% if view_name == "users:login" %}
          <p class="text-center"><a href="{% url 'users:password_reset' %}" class="text-center">{% trans "forgot_password" %}</a></p>
        {% endif %}
      </div>

      <!-- Чекбоксы -->
      {% for field in form %}
        {% if field.field.widget.input_type == "checkbox" %}
          <div class="form-check ms-auto me-auto mt-3">
            {{ field }}
            <label class="form-check-label" for="{{ field.id_for_label }}">
              {{ field.label }}
            </label>
          </div>
        {% endif %}
      {% endfor %}

      <!-- Общие ошибки формы -->
      {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger mt-2 text-center" role="alert">
            {{ error }}
          </div>
        {% endfor %}
      {% endif %}
    </div>

    <!-- Кнопка отправки и дополнительные ссылки -->
    <div class="d-flex flex-column text-center mt-4">
      <button class="btn btn-primary btn-lg w-100 py-2" type="submit">{{ submit_text }}</button>
    </div>

    <!-- Скрытые элементы -->
    <div class="d-none">
      <span id="serverTime">{{ server_time }}</span>
    </div>
  </form>
{% endwith %}